# Generated by Django 5.2.7 on 2026-08-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
